name: Bug report
description: Report a bug to help us improve. click here for a form
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the unexpected behavior here...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload screenshots to help explain your problem.
      render: image

  - type: input
    id: desktop-os
    attributes:
      label: Desktop OS
      placeholder: e.g. macOS, Windows 11, Ubuntu

  - type: input
    id: desktop-browser
    attributes:
      label: Desktop Browser
      placeholder: e.g. Chrome, Firefox, Safari

  - type: input
    id: desktop-version
    attributes:
      label: Desktop Browser Versio
